[Console] Create console layout
leductien-rightsvn/kmh pull request #21
Opened 2022-09-05 02:34 UTC by nguyenlephuckhang-rightsvn

### About this PR
Create template for console

### Displayed in web
![Screen Shot 2022-09-09 at 14 37 33](https://user-images.githubusercontent.com/103923118/189297787-5f8cd35c-7714-4035-8bef-9f85536d1652.png)

### Displayed in mobile
![Screen Shot 2022-09-09 at 14 37 58](https://user-images.githubusercontent.com/103923118/189297899-d86b896e-0f53-4d2c-96a6-7cb197595838.png)

### Issues
close #2: Create console layout

2022-09-13 09:46 UTC, nguyenthihao-rightsvn requested changes

2022-09-13 09:46 UTC, nguyenthihao-rightsvn commented on app/assets/stylesheets/application.css
> +  *= require_tree .
sao chỗ này thêm 1 space vậy em?

2022-09-13 09:46 UTC, nguyenthihao-rightsvn commented on app/assets/stylesheets/console/header.css
> +      position: sticky;
file này em fix lại 1 tab = 2 space giúp chị nha
hiện tại đang bị 4 space

2022-09-13 09:46 UTC, nguyenthihao-rightsvn commented on app/views/layouts/console/_content_header.html.erb
> +    <a class="navbar-brand"style="padding-left: 100px">  Navbar</a>
không dùng inline style nhé

2022-09-13 09:46 UTC, nguyenthihao-rightsvn commented on app/views/layouts/console/_content_header.html.erb
> +    <a class="navbar-brand"style="padding-left: 100px">  Navbar</a>
sao phải có space trước chữ `Navbar` vậy em
thẻ a sao không thấy link đi đâu nhỉ?

2022-09-13 09:46 UTC, nguyenthihao-rightsvn commented on app/views/layouts/console/_main_sidebar.html.erb
> +    <button
sửa indent của file này lại giúp chị

2022-09-13 09:46 UTC, nguyenthihao-rightsvn commented on app/views/layouts/console/application.html.erb
> +      <div id="ms-1" class="container">
ms-1 nghĩa là gì em? (đặt tên phải mang một ý nghĩa cho dễ đọc nha)

2022-09-14 02:18 UTC, nguyenlephuckhang-rightsvn commented on app/views/layouts/console/_main_sidebar.html.erb
> +    <button
dạ đã edit lại indent

2022-09-14 02:19 UTC, nguyenlephuckhang-rightsvn commented on app/assets/stylesheets/application.css
> +  *= require_tree .
dạ e đã remove những space dư r ạ

2022-09-14 02:19 UTC, nguyenlephuckhang-rightsvn commented on app/assets/stylesheets/console/header.css
> +      position: sticky;
dạ e đã edit lại tab 4 space rồi ạ

2022-09-14 02:37 UTC, nguyenlephuckhang-rightsvn commented on app/views/layouts/console/_content_header.html.erb
> +    <a class="navbar-brand"style="padding-left: 100px">  Navbar</a>
dạ đã edit

2022-09-14 02:37 UTC, nguyenlephuckhang-rightsvn commented on app/views/layouts/console/_main_sidebar.html.erb
> +    <button
dạ đã sữa

2022-09-14 02:38 UTC, nguyenlephuckhang-rightsvn commented on app/views/layouts/console/application.html.erb
> +      <div id="ms-1" class="container">
dạ e đã sửa lại tên

2022-09-21 04:10 UTC, leductien-rightsvn commented on app/assets/stylesheets/bootstrap_style.scss
> -@import "bootstrap";
ủa ren xoá cái ni

2022-09-21 04:10 UTC, leductien-rightsvn commented on app/helpers/dashboard_helper.rb
> +module DashboardHelper
ko dùng thì xoá đi cũng đc

2022-09-21 04:10 UTC, leductien-rightsvn commented on app/javascript/application.js
> +//= require jquery3
có import ở trên hết rồi mà

2022-09-21 04:10 UTC, leductien-rightsvn commented on app/views/console/dashboard/index.html.erb
> +<p>Day la index</p>
Thêm i18n các thứ, ghi cho đàng hoàng vô :p

2022-09-21 04:10 UTC, leductien-rightsvn commented on config/application.rb
> -    ENV['ACCESSABLE_HOSTS'].to_s.split(',').each do |host|
ren xoá đi

2022-09-21 04:10 UTC, leductien-rightsvn commented on db/schema.rb
> +ActiveRecord::Schema[7.0].define(version: 20_220_905_042_944) do
ren lại có thay đổi file ni

2022-09-21 04:24 UTC, leductien-rightsvn commented
thêm [.DS_Store](https://github.com/leductien-rightsvn/kmh/pull/21/files#diff-ca3423aa2cdacd9316177c4f0439ca56e86647426b5244f9ded77af6b6ccff41) vô .gitignore

2022-10-03 02:30 UTC, merged