[Model] Create a model Order Detail
leductien-rightsvn/kmh pull request #40
Opened 2022-10-03 03:03 UTC by nguyenlephuckhang-rightsvn

### About this PR
- Create a model Order Detail
### Notes

### Issues
close #10

#
Please review it ahihi ^^

2022-10-03 03:08 UTC, vuongvt-rights requested changes
Self check again please!

2022-10-03 03:09 UTC, nguyenlephuckhang-rightsvn commented
> Self check again please!

OK

2022-10-04 07:17 UTC, vuongvt-rights approved these changes

2022-10-04 07:38 UTC, leductien-rightsvn approved these changes

2022-10-04 07:38 UTC, merged